name: book_app
description: Book App.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  mobx: ^2.1.1
  flutter_mobx: ^2.0.6+4
  get_it: ^7.2.0
  http: ^0.13.5
  page_transition: ^2.0.9
  hive: ^2.2.3
  path_provider: ^2.0.12
  flutter_animate: ^4.1.1+1
  connectivity_plus: ^3.0.2
  another_flushbar: ^1.12.29
  auto_size_text: ^3.0.0
  google_fonts: ^4.0.3
  flutter_dotenv: ^5.0.2
  url_launcher: ^6.1.11
  share_plus: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  mobx_codegen: ^2.0.2
  build_runner: ^2.1.1
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/ 
    - .env
